package dal;

import dal.autoGenerated.BattleShipGame;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;
import java.io.File;

/**
 * Created by OFer.Spivak on 25/04/2017.
 */
public class DalImpl {

    public DalImpl(String path) {
        try {
            File file = new File(path);
            JAXBContext jaxbContext = JAXBContext.newInstance(BattleShipGame.class);
            Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
            BattleShipGame battleShipGame = (BattleShipGame) unmarshaller.unmarshal(file);
            System.out.println(battleShipGame.getGameType());
        } catch (Exception e) {
            System.out.println("Failed");
            System.out.println(e.getMessage());
        }
    }
}
